default:
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - docker info

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  script:
    - docker-compose up --build

after_script:
  - docker-compose down