image: docker:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose up --build

test:
  stage: test
  script:
    - echo "test phase here"

deploy:
  stage: deploy
  script:
    - docker-compose down
    - echo "deployment phase here"