stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run --rm service2.laurira npm test

deploy:
  stage: deploy
  script:
    - docker-compose up -d

