FROM node:16

WORKDIR /service2

COPY ./service2/service2.js ./service2.js
COPY ./service2/package.json ./package.json
COPY ./service2/package-lock.json ./package-lock.json

RUN npm install

EXPOSE 8000

CMD [ "node", "service2.js" ]