FROM node:16

WORKDIR /monitor

COPY ./monitor/monitor.js ./monitor.js
COPY ./monitor/package.json ./package.json
COPY ./monitor/package-lock.json ./package-lock.json

RUN npm install

COPY ./utils/wait-for-it.sh ./monitor/wait-for-it.sh
RUN chmod +x ./monitor/wait-for-it.sh

CMD ["./monitor/wait-for-it.sh", "rabbitmq:5672",  "--timeout=0", "--", "node", "monitor.js"]

