FROM python:3.9

WORKDIR /service1

COPY ./service1/service1.py ./service1.py
COPY ./service1/requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY ./utils/wait-for-it.sh ./service1/wait-for-it.sh
RUN chmod +x ./service1/wait-for-it.sh

# CMD [ "python", "service1.py" ]
CMD ["./service1/wait-for-it.sh", "rabbitmq:5672", "--", "python", "service1.py"]