FROM python:3.9

WORKDIR /service1

COPY ./service1/service1.py ./service1.py
COPY ./service1/requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY ./utils/wait-for-it.sh ./service1/wait-for-it.sh
RUN chmod +x ./service1/wait-for-it.sh

# Wait for monitor and service2 before starting the messaging process
CMD ["./service1/wait-for-it.sh", "service2:8000", "--timeout=5", "--", "./service1/wait-for-it.sh", "monitor:8087", "--timeout=5", "--", "python", "service1.py"]