FROM node:16

WORKDIR /service2

COPY ./service2/service2.js ./service2.js
COPY ./service2/package.json ./package.json
COPY ./service2/package-lock.json ./package-lock.json

RUN npm install

COPY ./utils/wait-for-it.sh ./service2/wait-for-it.sh
RUN chmod +x ./service2/wait-for-it.sh

EXPOSE 8000

# Wait for rabbitmq to be up
CMD ["./service2/wait-for-it.sh", "rabbitmq:5672", "--timeout=0", "--", "node", "service2.js"]